output_root: '../'
pytorch_data_dir: 'D:/workspace/datadrive/pytorch-data/'
experiment_name: "faces"
res: 160
batch_size: 20
num_workers: 10
start: 60
end: 150

model_paths:
  - "../faces.ckpt"

defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

hydra:
  run:
    dir: "."
  output_subdir: null