output_root: '../'
pytorch_data_dir: 'C:/workspace/datadrive/pytorch-data/'
experiment_name: "cars"

num_workers: 10
batch_size: 30
res: 304
start: 60
end: 150

model_paths:
  - "../../test/cars30.ckpt"

defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

hydra:
  run:
    dir: "."
  output_subdir: null