arch: dino
aug_alignment_weight: 0.0
batch_size: 5
checkpoint_freq: 1
continuous: true
correspondence_weight: 1.0
defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
dim: 70
dino_feat_type: feat
dino_patch_size: 8
dir_dataset_n_classes: 100
dir_dataset_name: cars
dropout: true
experiment_name: cars
extra_clusters: 0
feature_samples: 11
granularity: 1
hydra:
  output_subdir: null
  run:
    dir: .
lr: 5e-4
max_epochs: 2
model_type: vit_small
neg_inter_shift: 0.46
neg_inter_weight: 0.63
neg_samples: 5
num_workers: 2
output_root: ../
pointwise: true
pos_inter_shift: 0.12
pos_inter_weight: 0.25
pos_intra_shift: 0.18
pos_intra_weight: 0.67
pretrained_weights: null
projection_type: nonlinear
pytorch_data_dir: C:/workspace/datadrive/pytorch-data/
rec_weight: 0.0
repulsion_weight: 0.0
res: 304
reset_probe_steps: null
stabalize: false
stop_at_zero: true
use_fit_model: false
use_recalibrator: false
use_salience: false
use_true_labels: false
zero_clamp: true
